version: '3.7'

services:
  hamaofficeapp_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 1325:1323
    volumes:
      - ./backend/data:/srv/data
    env_file:
      - ./backend/.env
    restart: always

  coturn:
    image: coturn/coturn:4.6
    network_mode: host
    command: >
      -n
      --listening-port=3478
      --fingerprint
      --use-auth-secret
      --static-auth-secret=${TURN_SECRET}
      --realm=${TURN_REALM}
      --min-port=49152
      --max-port=49172
      --no-cli
    restart: always
