version: '3.7'

services:
  hamaofficeapp_database:
    build:
      context: ./database
      dockerfile: Dockerfile
    #image: hamaoffice_database
    volumes:
     - hamaoffice_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGTZ=${PGTZ}
    restart: always

  hamaofficeapp_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #image: hamaofficeapp_backend
    ports:
      - 1324:1323
    restart: always

volumes:
  hamaoffice_db_data:
